### ISSUE TITLE
Add Sina Login Method

### ISSUE THREAD

**Issue by hwangjr** [a289459798/react-native-umshare#3]
UMeng support weibo login method, so why not to add the weibo login method?

**Comment by hwangjr** [comment]
also, it's time to update umeng sdk.

**Comment by a289459798** [comment]
主要是考虑到现在第三方登录的主要是微信和qq，所以没有去集成微博

**Comment by hwangjr** [comment]
我觉得，微博在大学生群体里面还是占比挺大，所以建议加上。。而且里面我也有看到部分代码已经实现，只不过不完整。

**Comment by VincentSuperper** [comment]
希望能集成微博的功能+1
