### ISSUE TITLE
可以写个微信支付吗

### ISSUE THREAD

**Issue by dongodngtang** [a289459798/react-native-umshare#5]
可以在之基础上自己扩展个支付功能吗

**Comment by dongodngtang** [comment]
我自己试试扩展一个吧，因为我先用了你们的库，公司需要接入微信支付，我用react-native-WeChat集成后，编译失败，报错: Linker command failed with exit code 1 (use -v to see invocation)。我查了一下是引用了重复的资源

**Comment by a289459798** [comment]
是的，可以删除一方相关重复的文件就行了
