### ISSUE TITLE
framework not found UMSocialCore for architecture arm64

### ISSUE THREAD

**Issue by VincentSuperper** [a289459798/react-native-umshare#6]
react-native link 之后xcode编译报这个错误

**Comment by a289459798** [comment]
设置 architecture 为No 试试

**Comment by VincentSuperper** [comment]
设置了architecture 为No之后出现了error: Invalid bitcode signature

**Comment by a289459798** [comment]
如果不用react-native-umshare 能正常编译吗？ 你要不加一下群吧161263093

**Comment by VincentSuperper** [comment]
已经编译成功了
