### ISSUE TITLE
android编译报错

### ISSUE THREAD

**Issue by VincentSuperper** [a289459798/react-native-umshare#7]
../node_modules/react-native-umshare/android/src/main/java/com/zzy/umshare/UMShareModulePackage.java:33: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
1 个错误
:react-native-umshare:compileReleaseJavaWithJavac FAILED

**Comment by VincentSuperper** [comment]
@a289459798

**Comment by a289459798** [comment]
恩，这个是已知的，你可以先把那个去掉不影响，react-native 0.47+ 版本的module 不需要复写该方法了

**Comment by VincentSuperper** [comment]
所以是直接把
@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
注释掉吗？

**Comment by a289459798** [comment]
是的

**Comment by VincentSuperper** [comment]
可是我注释掉了这个方法之后 调用UMShareModule的时候还是报错喔
